---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
  labels:
    name: grafana
---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    app: grafana
spec:
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "true"
    auth.anonymous:
      enabled: "true"
      org_role: "Viewer"
    security:
      admin_user: admin
      admin_password: admin
      allow_embedding: "true"
  route:
    spec:
      to:
        kind: Service
        name: grafana-service
      port:
        targetPort: 3000
